require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb' # for expo-secure-store

platform :ios, '10.0'

target 'parliament' do
  use_unimodules! # for expo-secure-store
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])



  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  target 'parliamentTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  #use_flipper!
  #post_install do |installer|
  #  flipper_post_install(installer)
  #end
  
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      end
    end
  end
  
end

target 'parliament-tvOS' do
  # Pods for parliament-tvOS

  target 'parliament-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
